### ISSUE TITLE
SDL_image.IMG_Load_RW fails on Mac with libs from fnalibs.tar.bz2

### ISSUE THREAD

**Issue by elisee** [flibitijibibo/FNA#275]
Using ``Texture2D.FromStream`` to load up a PNG texture from memory, FNA ends up calling ``SDL_image.IMG_Load_RW``. This works fine on Windows but fails with a ``System.DllNotFoundException`` on Mac mentioning ``SDL_image-2.0.0.dylib``.

I have this file and I've dutifully copied all the .dylibs in "fnalibs/osx" into my app's folder and apart from that, my app seems to work. I noticed there's no ``libpng*.dylib`` in there and I suspect that's the problem? Is this a file I'm supposed to add or find somewhere else? If so, we probably want to update the wiki to mention it.

**Comment by flibitijibibo** [comment]
SDL2_image on OSX uses ImageIO on OSX, so that's why it won't be looking for other dylibs. (You can check this with `otool -L libSDL2_image-2.0.0.dylib` just in case.

If this isn't being run with the script, that might be why it's not resolving correctly. You can actually get away with just having SDL2 and OpenAL Soft in the game folder since those just depend on system libs, but SDL2_image will have problems finding SDL2 if the DYLD_LIBRARY_PATH isn't set correctly (the MonoKickstart script fixes this). This should be fixed either by running with the script, or copying the libs to somewhere like /usr/local/lib/ and having the dylibs always resolve correctly, whether you're running with the kick binaries or not.

**Comment by elisee** [comment]
Ah, I see. I'm currently building and running with the debugger in Xamarin Studio to hunt down platform-specific issues so I'm indeed not running with MonoKickstart. Thanks a lot for all the (quick!) replies so far and for your great work on FNA!
