### ISSUE TITLE
[TextInputEXT] Dead keys are not handled properly on Windows

### ISSUE THREAD

**Issue by elisee** [flibitijibibo/FNA#277]
Context: On Windows, using a French AZERTY keyboard, the ^ key is a commonly used [dead key](http://en.wikipedia.org/wiki/Dead_key) that people use to compose characters like ê, â, î, etc. by pressing ^ then the proper letter key.

----

SDL2 seems to have support for dead keys through the ``SDL_TEXTEDITING`` event [as explained on the wiki](https://wiki.libsdl.org/SDL_TextInputEvent) (**EDIT: this is wrong, SDL_TEXTEDITING is about IME, not dead keys**) but somehow my ^ key is reported right away via ``SDL_TEXTINPUT`` instead and never gets composed with the letter I press afterwards.

I tried adding a ``SDL_TEXTEDITING`` case to the ``SDL_PollEvent`` switch but FNA simply never gets those events. I also tried adding a call to ``SDL_StartTextInput`` when the main loop starts since it's supposedly required to get unicode input:

> This function will start accepting Unicode text input events in the focused SDL window, and start emitting SDL_TEXTINPUT and SDL_TEXTEDITING events.

but that didn't help, so I went digging into SDL's Windows-specific code:

https://github.com/spurious/SDL-mirror/blob/7f5d524dca8bd2cfa1603c0ae2d6f52c18d53348/src/video/windows/SDL_windowskeyboard.c#L160

Looks like there's a ``SDL_DISABLE_WINDOWS_IME`` define. It's for disabling [Input Method Editor](http://en.wikipedia.org/wiki/Input_method) which is not exactly conceptually the same as dead keys but since [this is the only place](https://github.com/spurious/SDL-mirror/blob/7f5d524dca8bd2cfa1603c0ae2d6f52c18d53348/src/video/windows/SDL_windowskeyboard.c#L842) that emits SDL_TEXTEDITING events, I'm guessing they might be one and the same for Windows.

Do you happen to know if ``SDL_DISABLE_WINDOWS_IME`` is defined in the Windows SDL2 build you provide with FNA? If not, I'll probably have to whip out my C compiler and try generating ``SDL_TEXTEDITING`` events using raw SDL2 but I thought I'd check with you first.

**Comment by Vodacek** [comment]
Same for Czech with ˇ and ´ for composing (ě, š, ř (try to speek this!), č, é, á, í, ú (we also have ů :-D) and other symbols), if this would work it will be great! For all this we can thank to http://en.wikipedia.org/wiki/Jan_Hus :-)
 
______________________________________________________________
> Od: "Elisée" <notifications@github.com>
> Komu: "flibitijibibo/FNA" <FNA@noreply.github.com>
> Datum: 02.01.2015 18:40
> Předmět: [FNA] SDL_TEXTEDITING events are never fired (at least on Windows) (#277)
>
Context: On Windows, using a French AZERTY keyboard, the ^ key is a commonly used dead key <http://en.wikipedia.org/wiki/Dead_key> that people use to compose characters like ê, â, î, etc. by pressing ^ then the proper letter key.
SDL2 seems to have support for dead keys through the SDL_TEXTEDITING event as explained on the wiki <https://wiki.libsdl.org/SDL_TextInputEvent> but somehow my ^ key is reported right away via SDL_TEXTINPUT instead and never gets composed with the letter I press afterwards.
I tried adding a SDL_TEXTEDITING case to the SDL_PollEvent switch but FNA simply never gets those events. I also tried adding a call to SDL_StartTextInput when the main loop starts since it's supposedly required to get unicode input:
This function will start accepting Unicode text input events in the focused SDL window, and start emitting SDL_TEXTINPUT and SDL_TEXTEDITING events.
but that didn't help, so I went digging into SDL's Windows-specific code:
https://github.com/spurious/SDL-mirror/blob/7f5d524dca8bd2cfa1603c0ae2d6f52c18d53348/src/video/windows/SDL_windowskeyboard.c#L160 <https://github.com/spurious/SDL-mirror/blob/7f5d524dca8bd2cfa1603c0ae2d6f52c18d53348/src/video/windows/SDL_windowskeyboard.c#L160>
Looks like there's a SDL_DISABLE_WINDOWS_IME define. It's for disabling Input Method Editor <http://en.wikipedia.org/wiki/Input_method> which is not exactly the same as dead keys but since this is the only place <https://github.com/spurious/SDL-mirror/blob/7f5d524dca8bd2cfa1603c0ae2d6f52c18d53348/src/video/windows/SDL_windowskeyboard.c#L842> that emits SDL_TEXTEDITING events, I'm guessing they are one and the same?
Do you happen to know if SDL_DISABLE_WINDOWS_IME is defined in the Windows SDL2 build you provide with FNA? If not, I'll probably have to whip out my C compiler and try generating SDL_TEXTEDITING events using raw SDL2 but I wanted to check with you first.

**Comment by flibitijibibo** [comment]
I've actually never seen all this before... the SDL mailing list will probably know what's up though.

**Comment by elisee** [comment]
I've tested on Linux and dead keys work fine. Will spend some time fiddling with SDL directly from C and see if I can reproduce / fix.

**Comment by elisee** [comment]
I can confirm the bug happens with bare SDL2 in C. I'm suspecting WM_DEADCHAR should be handled in the SDL2 Windows event loop. Now downloading DirectX SDK to try a fix.

**Comment by flibitijibibo** [comment]
Once you figure out what's up, send it over to the SDL Bugzilla:

https://bugzilla.libsdl.org/enter_bug.cgi

**Comment by elisee** [comment]
Done: https://bugzilla.libsdl.org/show_bug.cgi?id=2834

Turns out SDL_TEXTEDITING really is for IME only, so it's normal that it doesn't fire, but SDL_TEXTINPUT should compose dead keys properly. Hopefully my patch will hold up review and end up in the next SDL release.

As for me, I've rebuilt SDL2.dll for my own project based on the latest release + patch and it works!
(Feel free to close this if you think it's no longer useful to track it here.)

**Comment by flibitijibibo** [comment]
Will tag as an SDL thing and keep the issue up, in case someone else runs into this and needs the fix.

**Comment by flibitijibibo** [comment]
Has this been brought up on the SDL mailing list yet? If not I'll write something up for them today.

**Comment by elisee** [comment]
I didn't write to the mailing list, thought the bug report would be enough.

**Comment by flibitijibibo** [comment]
Just sent something to the ML. I'd link to it but the archive's really slow for me right now... will edit this post when I get it.

**Comment by flibitijibibo** [comment]
It looks like the mailing list is just totally hosed; you can send/receive message from it but the archive's just dead. Thanks DreamHost.

Ryan posted the SDL 2.0.4 TODO list, and it looks like this:

https://bugzilla.libsdl.org/buglist.cgi?keywords=triage-2.0.4

It may just be worth e-mailing/tweeting him directly linking to the patch, if necessary. 2.0.4's going to be a pretty important release for all three platforms, so it'd be nice to just have the default library do this correctly (and I can finally close this!).

**Comment by elisee** [comment]
Looks like the 2.0.4 was initially [planned for August 2014](https://forums.libsdl.org/viewtopic.php?t=10532&sid=a1a6a10ef4d47c315044a6f0c8e72617).

Should I pester icculus on Twitter? I'd be happy to help get the fix in but I'm not sure I'm comfortable being the random stranger that adds to his workload :)

**Comment by flibitijibibo** [comment]
You can always tell him I sent you... plus, it's a patch, so that helps too. ;P

**Comment by elisee** [comment]
It is done. :+1: https://twitter.com/icculus/status/569250071994347523

**Comment by flibitijibibo** [comment]
2.0.4's bug list is shrinking quickly, and it seems this has made it into the final few:

https://bugzilla.libsdl.org/show_bug.cgi?id=2834

Anyone who needs this in 2.0.4 should look at this patch and fix any remaining problems ASAP so we don't get cut at the last minute!

**Comment by flibitijibibo** [comment]
It looks like this got pushed to 2.0.5, seeing that the fix was actually a _previous_ iteration before what's currently being done. Anyone who's invested in this issue should dig into this _immediately_ after 2.0.4 hits, so that everyone who has their own fix for this can start mashing things together and maybe get working dead keys at last.

This and the SDL_GameController stuff discussed in the other issue could be things that we could have in a 2.0.4-FNA build between 4 and 5, with these two things being the only commits branched from the official tag, so if long release schedule have you waiting on this, I've decided to budge on this a bit specifically for FNA so we can move along to 1.0 before the end of this year.

**Comment by flibitijibibo** [comment]
Surprise! Looks like Sam merged @elisee's patch:

https://hg.libsdl.org/SDL/rev/02273530b7bf

So this should now be fixed in upstream SDL. You can either build from Hg, or wait for the 2.0.4 release (or even the next RC, which should be even sooner).

**Comment by elisee** [comment]
Just saw that, great news! :+1:
