### ISSUE TITLE
MonoGameJoystick.cfg is created in CWD on Windows, seems inappropriate

### ISSUE THREAD

**Issue by elisee** [flibitijibibo/FNA#280]
On Linux and OS X, The `MonoGameJoystick.cfg` file is properly created in home config subfolders (`~/Library/...` on OS X and `~/.config/MonoGame` on Linux) but on Windows, it's always created in the current working directory: https://github.com/flibitijibibo/FNA/blob/989be70ddd7ffb959467e7339ef5a95d2023e602/src/SDL2/Input/SDL2_GamePad.cs#L378

This is at odds with `StorageDevice`'s use of `Environment.SpecialFolder.MyDocuments` (https://github.com/flibitijibibo/FNA/blob/a6034dc9a00c6db3d848cd4cdea33989cdc931d4/src/Storage/StorageDevice.cs#L370). Was this an intentional decision? If not, several possibilities:

 * We can change it to try the application's folder and fail silently if it's not writable
 * Or we could have a dedicated folder in "My Documents"?

(Also, considering you removed MonoGame branding everywhere, would it make sense to rename MonoGameJoystick.cfg?)

**Comment by elisee** [comment]
BTW, to give some context/motivation for the change:

I'm offering people to auto-start my FNA app after the (WiX) installer is done, and it looks like the current working directory at this point is the desktop (because a shortcut was created there by the installer?), so I end up with a `MonoGameJoystick.cfg` file popping up on the desktop.

On the second launch through the desktop shortcut or by starting the EXE directly, the CWD is in `C:\Program Files (x86)\...` which isn't writable so my app just crashes on startup. Not ideal :D

**Comment by flibitijibibo** [comment]
The StorageDevice location is for XNA4 accuracy - were it any different, savegames wouldn't line up between XNA and FNA.

MonoGameJoystick is an odd thing, because it was really just a way for me to get configurable input for SDL_Joystick, back when we were still using SDL 1.2. After SDL_GameController went out, the config has largely stayed just in case the new config didn't get widely adopted. Which it has.

The Windows location was mostly because I didn't want to make directories on Windows machines (Documents/MonoGame/ would have been annoying, and %APPDATA%/Roaming/MonoGame would have been silent and also still annoying), and the locked location was because I wanted to retain compatibility with the standard that I went on to establish for >10 titles before even considering the rebrand.

I'm actually considering removing MonoGameJoystick and that whole fallback path for 1.0. Not much would change, except for a lot of deleted lines and changing `jdevice` event handling to `cdevice` event handling. MonoGame upstream doesn't seem interested in it, and that'd really be the only reason to keep this around. We'd be better off shipping controllertest.c as a bindings generator rather than having users muddle around with an XML file and Mysterious Joystick Numbering Systems(TM).

**Comment by elisee** [comment]
> After SDL_GameController went out, the config has largely stayed just in case the new config didn't get widely adopted.

What new config are you refering to? Another file?

Guess I'm just going to comment out the `MonoGameJoystick.cfg` creation on my end for now. I very much doubt anyone using my app would use it anyway.

**Comment by flibitijibibo** [comment]
This one:

https://wiki.libsdl.org/CategoryGameController

That is, there is no config file. There's a database of GUIDs where we remap everything to the 360 layout automatically, and we can pull in more GUIDs either from a third-party database (Steam's, for example) or from an environment variable that users can set, if they end up configuring new hardware not in the database.

Also, you might just be able to change this line to use `AppDomain.CurrentDomain.BaseDirectory`, rather than just the filename by itself:

https://github.com/flibitijibibo/FNA/blob/master/src/SDL2/Input/SDL2_GamePad.cs#L378

In any case, getting the working directory seems like a big deal... not sure how simple that is to do in C# compared to binreloc.c though.

**Comment by elisee** [comment]
> In any case, getting the working directory seems like a big deal... not sure how simple that is to do in C# compared to binreloc.c though.

You meant the executing assembly's containing folder, rather? `Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location)` would give us that. (The working directory would simply be `System.Environment.CurrentDirectory` but that doesn't get us anything, does it?)

**Comment by flibitijibibo** [comment]
I just changed that location to something that should make sense in any case:

https://github.com/flibitijibibo/FNA/blob/master/src/SDL2/Input/SDL2_GamePad.cs#L378

If `TitleContainer.Location` is wrong here, then we need to fix that value, not just this config's location. This should at least fix the desktop file; we'll address the removal of the config format separately.

**Comment by elisee** [comment]
Looks good. I think you'll want to add a `try/catch` block around the file creation at https://github.com/flibitijibibo/FNA/blob/master/src/SDL2/Input/SDL2_GamePad.cs#L434 since it's very much possible for the `TitleContainer.Location` to be read-only if it's in Program Files.

**Comment by flibitijibibo** [comment]
Do you get an `UnauthorizedAccessException` there? Just want to be sure I'm keeping the catch block limited to that case for error messages and such.

**Comment by elisee** [comment]
Yes, that's the one.

**Comment by flibitijibibo** [comment]
https://github.com/flibitijibibo/FNA/commit/c6dcdc89faaecf71e506a8095f990f3709df2ce5

I think this covers everything...?

**Comment by elisee** [comment]
Yup, tested to work. Thanks!

**Comment by flibitijibibo** [comment]
Not wholly related to the problems found here, but: I just pushed a test branch called `nomorecfg`:

https://github.com/flibitijibibo/FNA/tree/nomorecfg

This removes MonoGameJoystick in favor of requiring SDL_GameController mappings for all connected controllers. Test this out and see how it goes. (Hotplugging should be tested the hardest.)
