### ISSUE TITLE
shader normalmap not work

### ISSUE THREAD

**Issue by Predator75** [flibitijibibo/FNA#307]
Hi,
thanks for keep up FNA!!!!
I upload a zip archive here: https://www.dropbox.com/s/n5b1nguzmtmvhx4/XNA%20and%20FNA.zip?dl=0
there are two project
the original XNA
and the converted FNA
all works except for the first normalmap shader. press [space] to cycle effect
it is possibile to fix this problem?
regards

Predator

**Comment by Vodacek** [comment]
Hi,
I have similar issue, because MonoGame Pipeline can´t generate tangent space for models...
 
______________________________________________________________
> Od: Predator75 <notifications@github.com>
> Komu: "flibitijibibo/FNA" <FNA@noreply.github.com>
> Datum: 23.04.2015 19:18
> Předmět: [FNA] shader normalmap not work (#307)
>
Hi,
thanks for keep up FNA!!!!
I upload a zip archive here: https://www.dropbox.com/s/n5b1nguzmtmvhx4/XNA%20and%20FNA.zip?dl=0 <https://www.dropbox.com/s/n5b1nguzmtmvhx4/XNA%20and%20FNA.zip?dl=0>
there are two project
the original XNA
and the converted FNA
all works except for the first normalmap shader. press [space] to cycle effect
it is possibile to fix this problem?
regards
Predator

**Comment by flibitijibibo** [comment]
Looking at it with a debug binary, we get an ARB_debug_output error on generating the normalmap texture, because the SurfaceFormat is NormalizedByte4, which we hadn't verified yet. This has been fixed now:

https://github.com/flibitijibibo/FNA/commit/27a3c31af38f77f547e18c4451c2537a532b7d64

**Comment by Predator75** [comment]
YESSSSSS it's work! I'm very happy. Thank you for the fast fix
regards
Predator
