### ISSUE TITLE
DynamicSoundEffectInstance behavior incompatible with XNA4

### ISSUE THREAD

**Issue by Enichan** [flibitijibibo/FNA#320]
In XNA4 when Play is called on a DynamicSoundEffectInstance, its State property will be SoundState.Playing, even if no buffers are queued. This value persists (even if queueing no buffers) indefinitely, until Stop() is called. In FNA when a playing DynamicSoundEffectInstance has no buffers the State is set to SoundState.Stopped. This means that the following code which plays a sound under XNA4 will not work under FNA:

```c#
    snd = new DynamicSoundEffectInstance(44100, AudioChannels.Mono);
    snd.Play();
    snd.SubmitBuffer(CreateBuffer());
```

**Comment by flibitijibibo** [comment]
Oh, so it really does forcibly Play no matter what? That probably sounds heavenly when a PC can't play things:

https://github.com/flibitijibibo/FNA/blob/master/src/Media/Xiph/Song.cs#L314

This will take a fair amount of work to fix, because our internal Update depends very much on the idea of it stopping once we've hit the end of the buffer list:

https://github.com/flibitijibibo/FNA/blob/master/src/Audio/DynamicSoundEffectInstance.cs#L273

My recommendation is to either submit a couple buffers before playing or use BufferNeeded (the latter of which is what they wanted you to do anyway):

https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.audio.dynamicsoundeffectinstance.bufferneeded.aspx

**Comment by Enichan** [comment]
Yeah, this almost seems like one of those things where maybe being accurate to XNA4 isn't the best idea in the world. On the other hand, I do see why they went for this solution, in a threaded situation the sound may stop before your background thread filling buffers adds more, cutting off the sound entirely, which would be undesirable.

**Comment by flibitijibibo** [comment]
On the bright side, this did get me to look at the documentation one more time as well as AL accuracy:

https://github.com/flibitijibibo/FNA/commit/3250b6ca030be9fe0a8b9936a6ac80b02587439c
https://github.com/flibitijibibo/FNA/commit/fc0df4fbb0218b60c9850c37ce030133b30d339a
https://github.com/flibitijibibo/FNA/commit/3670357702996f29a6cd8d224d2bd1794c60ac93

**Comment by lagsalot** [comment]
Found my way here from playing Gnomoria under OS X, in which the sound cuts out consistently.  Is this related?  Is there a better place to bring up this bug/behavior?

**Comment by flibitijibibo** [comment]
I doubt it - the Gnomoria DynamicSoundEffectInstance only affects the music tracks, and cutouts there would mean skipping to entirely different songs. Odds are it's because the Mono runtime's garbage collector is halting all the threads, but that should only be for Boehm... the runtime I gave Rob uses SGen instead. In any case, that's more indicative of bad CPU or memory performance, rather than an issue with FNA's audio playback functionality.

**Comment by flibitijibibo** [comment]
Did you manage to work around this for MidBoss? I might be able to check this out for FNA 1.0 if I have time, but if you have the game working again then I'll just copy this issue over when recreating the repository and we'll deal with it later.

**Comment by Enichan** [comment]
Yeah I wound up scrapping the system I had because I found out I could use Renaud's OggStreamer stuff. Unlike MonoGame, it runs fine alongside FNA, so I'm good.

**Comment by flibitijibibo** [comment]
Turns out this wasn't terribly hard to fix anyway:

https://github.com/flibitijibibo/FNA/commit/ba5e1175f9eaac021b57cb635ac19d868f7ab63e

Now I can see why having it always Playing can be helpful, but detecting when it's stopped is kind of awful. Oh well...
