### ISSUE TITLE
OpenGL 3.2+ Core Profile support

### ISSUE THREAD

**Issue by renaudbedard** [flibitijibibo/FNA#321]
I was trying to use crytek's RenderDoc on my FNA game to do graphics debugging, and that tool only supports 3.2+ GL contexts, so I tried to make FNA create that using context attributes... and ran into a bunch of GL issues down the line.
I got past the enumeration of extensions (`glGetString(GL_EXTENSIONS)` isn't supported in Core) but now I'm hitting errors related to VAO/VBO usage that are going to be tricky to debug.

Is there any plan to support "modern" Core profile GL? Is it a downright bad idea to switch to that for compatibility/support?

**Comment by flibitijibibo** [comment]
I just got FEZ booting up with 3.2 Core - here's what has to change to support it:

- glGetString must be wrapped to use glGetStringi when available (3.0+).
- A vertex array object must be bound at the beginning of context creation when possible (3.0+). In theory we could try and cache these for VertexBufferBinding[] sets, but that'll basically ask for a whole new GLDevice.
- Client-side arrays can NOT be used, only VBOs are allowed (3.2+). This is something FNA can't really fix - we're not going to create a fake buffer behind the application's back. XNA has VertexBuffers in the spec, let's use them!

I was considering a ModernGLDevice at some point for this exact scenario, but with Vulkan coming along I opted to wait and see how usable that is for FNA - if it turns out a VulkanDevice doesn't really work, I'll work on a ModernGLDevice instead. It'll aim directly for GL 4.5+ and use every feature it possibly can (persistently mapped buffers, base vertex, VAOs, and so on). I'm pretty hopeful for Vulkan though.

**Comment by renaudbedard** [comment]
Understood, makes sense.
FEZ does use DrawUser[Indexed]Primitives all over the place so that would be a lot of work to port over.

I'll close the issue. :)

**Comment by flibitijibibo** [comment]
I've added support for the 3.2 Core Profile via FNA_OPENGL_FORCE_CORE_PROFILE, in the event that an FNA title does not use client-side arrays and would like to use tools like RenderDoc:

https://github.com/flibitijibibo/FNA/commit/a503f8eece534c8aac5deb88e88c8f549bda85dc
https://github.com/flibitijibibo/FNA/wiki/7:-FNA-Environment-Variables#fna_opengl_force_core_profile

**Comment by renaudbedard** [comment]
Cool, thanks!
