### ISSUE TITLE
[QUESTIONS] learning, using FNA

### ISSUE THREAD

**Issue by lewislepton** [flibitijibibo/FNA#330]
howdy.

since there is no forum i can see or the such. i thought i should ask here.
but as the title says, this is what im looking for.

with working with FNA, can i just follow XNA tutorials?
what coding platform should be good to use. can i use sublime, or visual studio code, or something else?
is there a special plugin for running applications, or is it just from the terminal?

i am on mac. im not a windows master race person [yet]. but just need some pointers more than anything since it shows how to get some things done [which is helpful], but not others

thanks

**Comment by lewislepton** [comment]
realistically, i just want to make sure about some things. ive just come across FNA, and it looks interesting, to say the least. plus if you can target other platforms, and not just xbox, but using the XNA motto, then thats cool ;)

**Comment by flibitijibibo** [comment]
FNA is meant to work as XNA does, so all documentation should apply. We don't support a content pipeline, however, so you'll be using raw assets. Shaders will have to be compiled with fxc.exe, which I happen to know works with Wine without any problems since FNA is developed almost entirely on Linux (mostly with vim, but MonoDevelop shows up when I have to use a debugger).

**Comment by lewislepton** [comment]
hey @flibitijibibo 
thanks very much for your help. good to know.

many thanks
