### ISSUE TITLE
FNA Binary Release

### ISSUE THREAD

**Issue by stonstad** [flibitijibibo/FNA#332]
Hello!  

Will there be a binary release of FNA?

Thanks,
Shaun

**Comment by flibitijibibo** [comment]
Nope! Official releases of FNA will come in zipped source form only. Due to .NET compiler/profile/runtime compatibility concerns, you will be expected to self-build with the same environment that you will use to ship your game. It's a single csproj file, however, so integration is just as simple as including a DLL.
